repos:
  - repo: https://github.com/ansys/pre-commit-hooks
    rev: v0.5.2
    hooks:
      - id: add-license-headers
        name: Add Popsize license header
        args:
          - --start_year=2023
          - --custom_template=popsize
          - --ignore_license_check
        files: \.(ts|tsx|js|jsx)$
        exclude: |
          (?x)^( 
            node_modules|build|public|prisma|extensions
          )/
