# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "92dbf9030973fdc215633134e48f4936"
name = "Popsize"
handle = "popsize"
application_url = "https://prior-jonathan-locally-covers.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "pubsub://popsizeDB:shopify-compliance-webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://prior-jonathan-locally-covers.trycloudflare.com/auth/callback",
  "https://prior-jonathan-locally-covers.trycloudflare.com/auth/shopify/callback",
  "https://prior-jonathan-locally-covers.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[app_preferences]
url = "https://partners.popsize.ai/"
