# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "92dbf9030973fdc215633134e48f4936"
name = "Popsize"
handle = "popsize"
application_url = "https://app-backend-503388092768.europe-west1.run.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://app-backend-503388092768.europe-west1.run.app/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://app-backend-503388092768.europe-west1.run.app/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "pubsub://popsizedb:shopify-compliance-webhooks"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "pubsub://popsizeb2b:shopify-subscription-change"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = ["https://app-backend-503388092768.europe-west1.run.app/auth/callback", "https://app-backend-503388092768.europe-west1.run.app/auth/shopify/callback", "https://app-backend-503388092768.europe-west1.run.app/api/auth/callback"]

[pos]
embedded = false

[app_preferences]
url = "https://partners.popsize.ai/"
